
package com.spacetravels.travels.ws.reservas;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ReservasWSImplService", targetNamespace = "http://reservas.ws.travels.spacetravels.com/", wsdlLocation = "http://localhost:9080/spacetarvels-travels/ReservasWS?wsdl")
public class ReservasWSImplService
    extends Service
{

    private final static URL RESERVASWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException RESERVASWSIMPLSERVICE_EXCEPTION;
    private final static QName RESERVASWSIMPLSERVICE_QNAME = new QName("http://reservas.ws.travels.spacetravels.com/", "ReservasWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/spacetarvels-travels/ReservasWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RESERVASWSIMPLSERVICE_WSDL_LOCATION = url;
        RESERVASWSIMPLSERVICE_EXCEPTION = e;
    }

    public ReservasWSImplService() {
        super(__getWsdlLocation(), RESERVASWSIMPLSERVICE_QNAME);
    }

    public ReservasWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), RESERVASWSIMPLSERVICE_QNAME, features);
    }

    public ReservasWSImplService(URL wsdlLocation) {
        super(wsdlLocation, RESERVASWSIMPLSERVICE_QNAME);
    }

    public ReservasWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RESERVASWSIMPLSERVICE_QNAME, features);
    }

    public ReservasWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReservasWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ReservasWS
     */
    @WebEndpoint(name = "ReservasWSImplPort")
    public ReservasWS getReservasWSImplPort() {
        return super.getPort(new QName("http://reservas.ws.travels.spacetravels.com/", "ReservasWSImplPort"), ReservasWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReservasWS
     */
    @WebEndpoint(name = "ReservasWSImplPort")
    public ReservasWS getReservasWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://reservas.ws.travels.spacetravels.com/", "ReservasWSImplPort"), ReservasWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RESERVASWSIMPLSERVICE_EXCEPTION!= null) {
            throw RESERVASWSIMPLSERVICE_EXCEPTION;
        }
        return RESERVASWSIMPLSERVICE_WSDL_LOCATION;
    }

}
