
package com.spacetravels.travels.ws.usuarios;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "UsuariosWSImplService", targetNamespace = "http://usuarios.ws.travels.spacetravels.com/", wsdlLocation = "http://localhost:9080/spacetarvels-travels/UsuariosWS?wsdl")
public class UsuariosWSImplService
    extends Service
{

    private final static URL USUARIOSWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException USUARIOSWSIMPLSERVICE_EXCEPTION;
    private final static QName USUARIOSWSIMPLSERVICE_QNAME = new QName("http://usuarios.ws.travels.spacetravels.com/", "UsuariosWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/spacetarvels-travels/UsuariosWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USUARIOSWSIMPLSERVICE_WSDL_LOCATION = url;
        USUARIOSWSIMPLSERVICE_EXCEPTION = e;
    }

    public UsuariosWSImplService() {
        super(__getWsdlLocation(), USUARIOSWSIMPLSERVICE_QNAME);
    }

    public UsuariosWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USUARIOSWSIMPLSERVICE_QNAME, features);
    }

    public UsuariosWSImplService(URL wsdlLocation) {
        super(wsdlLocation, USUARIOSWSIMPLSERVICE_QNAME);
    }

    public UsuariosWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USUARIOSWSIMPLSERVICE_QNAME, features);
    }

    public UsuariosWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UsuariosWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UsuariosWS
     */
    @WebEndpoint(name = "UsuariosWSImplPort")
    public UsuariosWS getUsuariosWSImplPort() {
        return super.getPort(new QName("http://usuarios.ws.travels.spacetravels.com/", "UsuariosWSImplPort"), UsuariosWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UsuariosWS
     */
    @WebEndpoint(name = "UsuariosWSImplPort")
    public UsuariosWS getUsuariosWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://usuarios.ws.travels.spacetravels.com/", "UsuariosWSImplPort"), UsuariosWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USUARIOSWSIMPLSERVICE_EXCEPTION!= null) {
            throw USUARIOSWSIMPLSERVICE_EXCEPTION;
        }
        return USUARIOSWSIMPLSERVICE_WSDL_LOCATION;
    }

}
