
package com.spacetravels.travels.ws.usuarios;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UsuariosWS", targetNamespace = "http://usuarios.ws.travels.spacetravels.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UsuariosWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.spacetravels.travels.ws.usuarios.Usuarios
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registerUser", targetNamespace = "http://usuarios.ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.usuarios.RegisterUser")
    @ResponseWrapper(localName = "registerUserResponse", targetNamespace = "http://usuarios.ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.usuarios.RegisterUserResponse")
    public Usuarios registerUser(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuarios arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.spacetravels.travels.ws.usuarios.Usuarios>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerUsuarios", targetNamespace = "http://usuarios.ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.usuarios.ObtenerUsuarios")
    @ResponseWrapper(localName = "obtenerUsuariosResponse", targetNamespace = "http://usuarios.ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.usuarios.ObtenerUsuariosResponse")
    public List<Usuarios> obtenerUsuarios();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.spacetravels.travels.ws.usuarios.Usuarios
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://usuarios.ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.usuarios.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://usuarios.ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.usuarios.LoginResponse")
    public Usuarios login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
