
package com.spacetravels.travels.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ViajesWSImplService", targetNamespace = "http://ws.travels.spacetravels.com/", wsdlLocation = "http://localhost:9080/spacetarvels-travels/ViajesWS?wsdl")
public class ViajesWSImplService
    extends Service
{

    private final static URL VIAJESWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException VIAJESWSIMPLSERVICE_EXCEPTION;
    private final static QName VIAJESWSIMPLSERVICE_QNAME = new QName("http://ws.travels.spacetravels.com/", "ViajesWSImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9080/spacetarvels-travels/ViajesWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VIAJESWSIMPLSERVICE_WSDL_LOCATION = url;
        VIAJESWSIMPLSERVICE_EXCEPTION = e;
    }

    public ViajesWSImplService() {
        super(__getWsdlLocation(), VIAJESWSIMPLSERVICE_QNAME);
    }

    public ViajesWSImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VIAJESWSIMPLSERVICE_QNAME, features);
    }

    public ViajesWSImplService(URL wsdlLocation) {
        super(wsdlLocation, VIAJESWSIMPLSERVICE_QNAME);
    }

    public ViajesWSImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VIAJESWSIMPLSERVICE_QNAME, features);
    }

    public ViajesWSImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ViajesWSImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ViajesWS
     */
    @WebEndpoint(name = "ViajesWSImplPort")
    public ViajesWS getViajesWSImplPort() {
        return super.getPort(new QName("http://ws.travels.spacetravels.com/", "ViajesWSImplPort"), ViajesWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ViajesWS
     */
    @WebEndpoint(name = "ViajesWSImplPort")
    public ViajesWS getViajesWSImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.travels.spacetravels.com/", "ViajesWSImplPort"), ViajesWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VIAJESWSIMPLSERVICE_EXCEPTION!= null) {
            throw VIAJESWSIMPLSERVICE_EXCEPTION;
        }
        return VIAJESWSIMPLSERVICE_WSDL_LOCATION;
    }

}
