
package com.spacetravels.travels.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ViajesWS", targetNamespace = "http://ws.travels.spacetravels.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ViajesWS {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.spacetravels.travels.ws.Viajes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTodosViajesOrigen", targetNamespace = "http://ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.ObtenerTodosViajesOrigen")
    @ResponseWrapper(localName = "obtenerTodosViajesOrigenResponse", targetNamespace = "http://ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.ObtenerTodosViajesOrigenResponse")
    public List<Viajes> obtenerTodosViajesOrigen(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.spacetravels.travels.ws.Viajes
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "crearViaje", targetNamespace = "http://ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.CrearViaje")
    @ResponseWrapper(localName = "crearViajeResponse", targetNamespace = "http://ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.CrearViajeResponse")
    public Viajes crearViaje(
        @WebParam(name = "arg0", targetNamespace = "")
        Viajes arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.spacetravels.travels.ws.Viajes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTodosViajesDestino", targetNamespace = "http://ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.ObtenerTodosViajesDestino")
    @ResponseWrapper(localName = "obtenerTodosViajesDestinoResponse", targetNamespace = "http://ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.ObtenerTodosViajesDestinoResponse")
    public List<Viajes> obtenerTodosViajesDestino(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<com.spacetravels.travels.ws.Viajes>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obtenerTodosViajes", targetNamespace = "http://ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.ObtenerTodosViajes")
    @ResponseWrapper(localName = "obtenerTodosViajesResponse", targetNamespace = "http://ws.travels.spacetravels.com/", className = "com.spacetravels.travels.ws.ObtenerTodosViajesResponse")
    public List<Viajes> obtenerTodosViajes();

}
